service: iclinics

frameworkVersion: '3'

plugins:
  - serverless-jetpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  memorySize: 512

functions:
  api:
    handler: dist/serverless.handler
    events:
      - http:
          method: any
          path: /{proxy+}

custom:
  serverless-offline:
    noPrependStageInUrl: true