# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  setup_and_test:
    docker:
      - image: cimg/node:18.13.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run tests
          command: yarn test:cov
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy_to_production:
    docker:
      - image: cimg/node:18.13.0
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: build
          command: yarn build
      - run:
          name: deploy
          command: yarn deploy

workflows:
  build:
    jobs:
      - setup_and_test:
          filters:
            branches:
              only:
                - main

      - hold_for_deploy_to_production:
          type: approval
          requires:
            - setup_and_test
          filters:
            branches:
              only:
                - main

      - deploy_to_production:
          context:
            - aws-credentials
          requires:
            - setup_and_test
            - hold_for_deploy_to_production
          filters:
            branches:
              only:
                - main